<?php
namespace App;

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',  
  'CORS_ALLOW_ORIGIN' => '^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$',
  

);