<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => '7cbfd5f81049d0bc8a3747e282fd8771',
  'CORS_ALLOW_ORIGIN' => '^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$',
  'DATABASE_URL' => 'mysql://eco_user:iteco@127.0.0.1:3306/ecoit_db1?serverVersion=mariadb-10.5.8',
  'MESSENGER_TRANSPORT_DSN'=>'doctrine://default'

);